FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python3 -m pip install --upgrade pip --no-cache-dir

RUN pip3 install numpy pandas h5py scipy anndata scanpy zarr fire scikit-image git+https://github.com/BioinfoTongLI/spatialdata-io.git@main
