FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python -m pip install --upgrade pip --no-cache-dir

RUN pip install pre-commit fire
RUN git clone https://github.com/ome/ome-zarr-metadata.git /opt/ome-zarr-metadata && \
	cd /opt/ome-zarr-metadata && \
	pre-commit install && \
	pip install -e .
