name: webatlas
channels:
  - conda-forge
  - nodefaults
  - bioconda
dependencies:
  - anndata==0.12.6
  - fire==0.5.0
  - h5py==3.10.0
  - numpy==1.26.4
  - ome-zarr==0.13.0
  - ome::bioformats2raw-libs==0.7.0
  - ome::bioformats2raw==0.7.0
  - ome::raw2ometiff-libs==0.5.0=0
  - ome::raw2ometiff==0.5.0=0
  - pandas==2.1.0
  - pillow==10.1.0
  - pip==23.2.1
  - python==3.11.14
  - pyvips==2.2.1
  - regex==2023.8.8
  - rioxarray==0.15.0
  - scanpy==1.11.0
  - scikit-image==0.22.0
  - scipy==1.14.1
  - tifffile==2023.9.26
  - xmlschema==2.5.0
  - zarr==3.1.5
