name: python-tests

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libvips
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Clone ome-zarr-metadata
        uses: actions/checkout@v2
        with:
          repository: ome/ome-zarr-metadata
          path: ./ome-zarr-metadata
          submodules: recursive
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./envs/requirements.txt
          pip install -r ./envs/dev/requirements.txt
          cd ./ome-zarr-metadata && pre-commit install && pip install -e . && cd ../
      - name: Run tests
        run: python -m pytest --cov=bin tests/
        env:
          PYTHONPATH: ./bin
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
